import { useState } from 'react';
import { AIInsight, JournalInteraction } from '../types';
import { askGeminiInsights } from '../lib/gemini';
import {
  Lightbulb,
  Sparkles,
  TrendingUp,
  ShieldAlert,
  Compass,
  CheckCircle,
  Clock,
  Trash2,
  AlertCircle,
} from 'lucide-react';

interface InsightsViewProps {
  userId: string;
  interactions: JournalInteraction[];
  insights: AIInsight[];
  onSaveInsight: (insight: AIInsight) => Promise<void>;
  onDeleteInsight: (insightId: string) => Promise<void>;
}

export function InsightsView({
  userId,
  interactions,
  insights,
  onSaveInsight,
  onDeleteInsight,
}: InsightsViewProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (interactions.length === 0) {
      setErrorMessage('Please create at least one reflection entry before generating AI insights.');
      return;
    }

    setIsGenerating(true);
    setErrorMessage(null);

    try {
      // Compile user reflections safely
      const payload = interactions.map((i) => ({
        title: i.title,
        summary: i.summary,
        text: i.turns.map((t) => `${t.role}: ${t.text}`).join('\n'),
        tags: i.tags,
        createdAt: i.createdAt,
      }));

      const res = await askGeminiInsights(payload);
      const data = res.data;

      const newInsight: AIInsight = {
        id: 'ins_' + Date.now(),
        userId,
        generatedAt: Date.now(),
        summary: data.summary || 'Insight synthesis across your reflections.',
        recurringThemes: data.recurringThemes || [],
        commonConcerns: data.commonConcerns || [],
        positivePatterns: data.positivePatterns || [],
        improvementAreas: data.improvementAreas || [],
        observations: data.observations || [],
        suggestedActions: data.suggestedActions || [],
        modelUsed: res.modelUsed || 'gemini-3.6-flash',
      };

      await onSaveInsight(newInsight);
    } catch (err: any) {
      console.error('Error generating insights:', err);
      setErrorMessage(err?.message || 'Failed to generate insights with Gemini.');
    } finally {
      setIsGenerating(false);
    }
  };

  const currentInsight = insights[0] || null;

  return (
    <div className="space-y-8 pb-12 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-white/5 pb-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-serif italic text-white tracking-tight">
            AI Insight Engine
          </h1>
          <p className="mt-1 text-xs text-white/50">
            Uncover recurring cognitive themes, latent bottlenecks, and compounding strengths across your journal.
          </p>
        </div>

        <button
          id="run-insight-engine-btn"
          onClick={handleGenerate}
          disabled={isGenerating || interactions.length === 0}
          className="flex items-center gap-2 rounded-xl bg-amber-600 px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-amber-600/20 hover:bg-amber-500 transition-all disabled:opacity-40 cursor-pointer self-start sm:self-auto"
        >
          <Sparkles className="h-4 w-4" />
          <span>{isGenerating ? 'Analyzing Reflections...' : 'Generate New Insights'}</span>
        </button>
      </div>

      {/* Mandatory Distinction & Non-Diagnostic Banner */}
      <div className="rounded-xl border border-amber-500/20 bg-amber-950/10 p-3.5 flex items-start gap-3 text-xs text-amber-200/90">
        <Lightbulb className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
        <div className="leading-relaxed">
          <strong className="text-amber-300 font-semibold">AI Synthesis Notice:</strong> All insights are generated by Gemini models analyzing strictly your private journal interactions. These provide reflective meta-cognition and productivity perspective, and are strictly non-diagnostic and non-medical.
        </div>
      </div>

      {errorMessage && (
        <div className="flex items-center gap-2 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3 text-xs text-rose-300">
          <AlertCircle className="h-4 w-4 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Current Insight Showcase */}
      {currentInsight ? (
        <div className="space-y-6">
          {/* Executive Synthesis */}
          <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-6 space-y-3">
            <div className="flex items-center justify-between text-[11px] text-white/40">
              <span className="flex items-center gap-1.5 font-mono">
                <Clock className="h-3.5 w-3.5 text-indigo-400" />
                Synthesized {new Date(currentInsight.generatedAt).toLocaleDateString()} at{' '}
                {new Date(currentInsight.generatedAt).toLocaleTimeString([], {
                  hour: '2-digit',
                  minute: '2-digit',
                })}
              </span>
            </div>

            <h2 className="text-sm font-semibold uppercase tracking-wider text-indigo-300">
              Executive Trajectory &amp; Mindset
            </h2>
            <p className="text-sm font-serif italic text-white/90 leading-relaxed">
              "{currentInsight.summary}"
            </p>
          </div>

          {/* 4-Box Grid: Themes, Concerns, Strengths, Growth */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {/* Recurring Themes */}
            <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-5 space-y-3">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-indigo-400">
                <Compass className="h-4 w-4" />
                <span>Recurring Themes</span>
              </div>
              <div className="flex flex-wrap gap-2 pt-1">
                {(currentInsight.recurringThemes || []).map((theme, i) => (
                  <span
                    key={i}
                    className="rounded-xl border border-indigo-500/20 bg-indigo-500/10 px-3 py-1.5 text-xs text-indigo-200 font-medium"
                  >
                    {theme}
                  </span>
                ))}
              </div>
            </div>

            {/* Positive Patterns & Strengths */}
            <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-5 space-y-3">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-emerald-400">
                <TrendingUp className="h-4 w-4" />
                <span>Positive Cognitive Patterns</span>
              </div>
              <ul className="space-y-2 text-xs text-white/80 list-disc list-inside">
                {(currentInsight.positivePatterns || []).map((pattern, i) => (
                  <li key={i} className="leading-relaxed">
                    {pattern}
                  </li>
                ))}
              </ul>
            </div>

            {/* Common Concerns / Bottlenecks */}
            <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-5 space-y-3">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-amber-400">
                <ShieldAlert className="h-4 w-4" />
                <span>Observed Bottlenecks &amp; Dilemmas</span>
              </div>
              <ul className="space-y-2 text-xs text-white/80 list-disc list-inside">
                {(currentInsight.commonConcerns || []).map((concern, i) => (
                  <li key={i} className="leading-relaxed">
                    {concern}
                  </li>
                ))}
              </ul>
            </div>

            {/* Growth Areas & High-Leverage Actions */}
            <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-5 space-y-3">
              <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-purple-400">
                <CheckCircle className="h-4 w-4" />
                <span>High-Leverage Recommendations</span>
              </div>
              <ul className="space-y-2 text-xs text-white/80 list-disc list-inside">
                {(currentInsight.suggestedActions || []).map((action, i) => (
                  <li key={i} className="leading-relaxed">
                    {action}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="rounded-2xl border border-dashed border-white/10 p-12 text-center space-y-3">
          <Lightbulb className="h-8 w-8 text-amber-400/40 mx-auto" />
          <h3 className="text-sm font-semibold text-white">No Insights Generated Yet</h3>
          <p className="text-xs text-white/50 max-w-md mx-auto leading-relaxed">
            As you log journal entries and decisions, click "Generate New Insights" to allow Gemini to identify recurring themes, blind spots, and habit loops.
          </p>
          {interactions.length > 0 && (
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="mt-2 inline-flex items-center gap-2 rounded-xl bg-amber-600 px-4 py-2 text-xs font-semibold text-white hover:bg-amber-500 cursor-pointer"
            >
              <Sparkles className="h-3.5 w-3.5" />
              <span>Run First Synthesis</span>
            </button>
          )}
        </div>
      )}

      {/* Historic Insights Archive */}
      {insights.length > 1 && (
        <div className="space-y-4 pt-6 border-t border-white/5">
          <h3 className="text-xs font-semibold uppercase tracking-wider text-white/60">
            Historical Syntheses Archive ({insights.length})
          </h3>
          <div className="space-y-3">
            {insights.slice(1).map((insight) => (
              <div
                key={insight.id}
                className="flex items-center justify-between rounded-xl border border-white/5 bg-white/[0.02] p-4 text-xs"
              >
                <div>
                  <div className="text-[10px] text-white/40 font-mono">
                    {new Date(insight.generatedAt).toLocaleDateString()}
                  </div>
                  <p className="text-white/80 line-clamp-1 mt-0.5 font-serif italic">
                    "{insight.summary}"
                  </p>
                </div>
                <button
                  onClick={() => onDeleteInsight(insight.id)}
                  className="p-1.5 text-white/30 hover:text-rose-400 cursor-pointer"
                  title="Delete Insight"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
